# Generated by Django 4.0.4 on 2022-05-03 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cabeza',
            fields=[
                ('idcabeza', models.AutoField(primary_key=True, serialize=False)),
                ('comprovante', models.CharField(max_length=45)),
                ('precios', models.CharField(max_length=45)),
                ('fecha', models.CharField(max_length=45)),
                ('establecimiento', models.CharField(max_length=45)),
                ('persona_idpersona', models.IntegerField()),
            ],
            options={
                'db_table': 'cabeza',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Cuerpo',
            fields=[
                ('idcuerpo', models.IntegerField(primary_key=True, serialize=False)),
                ('sub_factura', models.CharField(max_length=45)),
                ('sub_total', models.CharField(max_length=45)),
                ('iva', models.CharField(max_length=45)),
                ('total_factura', models.CharField(max_length=45)),
                ('cabeza_factura_idcabeza', models.IntegerField(db_column='Cabeza_factura_idCabeza')),
            ],
            options={
                'db_table': 'cuerpo',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Desparacitacion',
            fields=[
                ('iddesparacitacion', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre_medicamento', models.CharField(max_length=45)),
                ('lote', models.CharField(max_length=45)),
                ('labaratorio', models.CharField(max_length=45)),
                ('fecha', models.CharField(max_length=45)),
                ('proximafecha', models.CharField(max_length=45)),
                ('especie_idespecie', models.IntegerField(db_column='Especie_idEspecie')),
            ],
            options={
                'db_table': 'desparacitacion',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Enfermedades',
            fields=[
                ('idenfermedades', models.AutoField(primary_key=True, serialize=False)),
                ('tipo_enfermedad', models.CharField(max_length=45)),
                ('casos', models.CharField(max_length=45)),
                ('descripcion', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'enfermedades',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Especie',
            fields=[
                ('idespecie', models.IntegerField(db_column='idEspecie', primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=45)),
                ('descripcion', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'especie',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EsquemaVanucacion',
            fields=[
                ('idesquema_vanucacion', models.IntegerField(db_column='idesquema vanucacion', primary_key=True, serialize=False)),
                ('nombre_vacuna', models.CharField(max_length=45)),
                ('dosis', models.CharField(max_length=45)),
                ('especie_idespecie', models.IntegerField(db_column='Especie_idEspecie')),
            ],
            options={
                'db_table': 'esquema vanucacion',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Evoluciones',
            fields=[
                ('idevoluciones', models.IntegerField(primary_key=True, serialize=False)),
                ('tipo_evolucion', models.CharField(max_length=45)),
                ('parte_medico', models.CharField(max_length=45)),
                ('descripcion', models.CharField(max_length=45)),
                ('procedimientos_idprocedimientos', models.IntegerField(db_column='Procedimientos_idProcedimientos')),
                ('medicamentos_idmedicamentos', models.IntegerField()),
            ],
            options={
                'db_table': 'evoluciones',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='HistoriaClinica',
            fields=[
                ('idhistoria_clinica', models.IntegerField(primary_key=True, serialize=False)),
                ('mascota_idmascota', models.IntegerField(db_column='Mascota_idMascota')),
                ('ingreso_idingreso', models.IntegerField()),
                ('desparacitacion_iddesparacitacion', models.IntegerField()),
                ('vacunacion_idvacunacion', models.IntegerField()),
                ('resumen_del_servicio_idresumen_del_servicio', models.IntegerField(db_column='resumen del servicio_idresumen del servicio')),
            ],
            options={
                'db_table': 'historia_clinica',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Ingreso',
            fields=[
                ('idingreso', models.AutoField(primary_key=True, serialize=False)),
                ('lugar', models.CharField(max_length=45)),
                ('fecha', models.CharField(max_length=45)),
                ('hora', models.CharField(max_length=45)),
                ('sintomas', models.CharField(max_length=45)),
                ('comportamientos', models.CharField(max_length=45)),
                ('descripcion', models.CharField(max_length=45)),
                ('evoluciones_idevoluciones', models.IntegerField()),
                ('enfermedades_idenfermedades', models.IntegerField()),
            ],
            options={
                'db_table': 'ingreso',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Mascota',
            fields=[
                ('idmascota', models.AutoField(db_column='idMascota', primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=45)),
                ('sexo', models.CharField(max_length=45)),
                ('fecha_nacimiento', models.CharField(max_length=45)),
                ('alimentacion', models.CharField(max_length=45)),
                ('habitad', models.CharField(max_length=45)),
                ('comportamientos', models.CharField(max_length=45)),
                ('sintomas', models.CharField(max_length=45)),
                ('caracteristicas_fisicas', models.CharField(max_length=45)),
                ('persona_idpersona', models.IntegerField(db_column='Persona_idPersona')),
                ('especie_idespecie', models.IntegerField(db_column='Especie_idEspecie')),
                ('raza_idraza', models.IntegerField()),
            ],
            options={
                'db_table': 'mascota',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Medicamentos',
            fields=[
                ('idmedicamentos', models.AutoField(primary_key=True, serialize=False)),
                ('tipo_medicamento', models.CharField(max_length=45)),
                ('administracion', models.CharField(max_length=45)),
                ('aplicacion', models.CharField(max_length=45)),
                ('fecha', models.CharField(max_length=45)),
                ('dosis', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'medicamentos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('idpersona', models.AutoField(primary_key=True, serialize=False)),
                ('primer_nombre', models.CharField(max_length=45)),
                ('segundo_nombre', models.CharField(max_length=45)),
                ('apellidos', models.CharField(max_length=45)),
                ('correo', models.CharField(max_length=45)),
                ('documento', models.CharField(max_length=45)),
                ('direccion', models.CharField(max_length=45)),
                ('telefono', models.CharField(max_length=45)),
                ('genero', models.CharField(max_length=45)),
                ('fecha_nacimiento', models.CharField(max_length=45)),
                ('tipo_persona_idtipo_persona', models.IntegerField(db_column='Tipo_persona_idTipo_persona')),
            ],
            options={
                'db_table': 'persona',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Procedimientos',
            fields=[
                ('idprocedimientos', models.AutoField(db_column='idProcedimientos', primary_key=True, serialize=False)),
                ('tipo_procedimieno', models.CharField(max_length=45)),
                ('fecha', models.CharField(max_length=45)),
                ('resultados', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'procedimientos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Raza',
            fields=[
                ('idraza', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=45)),
                ('descripcion', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'raza',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ResumenDelServicio',
            fields=[
                ('idresumen_del_servicio', models.IntegerField(db_column='idresumen del servicio', primary_key=True, serialize=False)),
                ('descripcionservicio', models.CharField(max_length=45)),
                ('productosutilizados', models.CharField(max_length=45)),
                ('elementosutilizados', models.CharField(max_length=45)),
                ('servicios_idservicios', models.IntegerField()),
            ],
            options={
                'db_table': 'resumen del servicio',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Servicios',
            fields=[
                ('idservicios', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=45)),
                ('descripcion', models.CharField(max_length=45)),
                ('cabeza_factura_idcabeza_factura', models.IntegerField()),
            ],
            options={
                'db_table': 'servicios',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TipoPersona',
            fields=[
                ('idtipo_persona', models.AutoField(db_column='idTipo_persona', primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=45)),
                ('descripcion', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'tipo_persona',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Vacunacion',
            fields=[
                ('idvacunacion', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=45)),
                ('lote', models.CharField(max_length=45)),
                ('fecha', models.CharField(max_length=45)),
                ('proxima_vacuna', models.CharField(db_column='proxima vacuna', max_length=45)),
                ('esquema_vanucacion_idesquema_vanucacion', models.IntegerField(db_column='esquema vanucacion_idesquema vanucacion')),
            ],
            options={
                'db_table': 'vacunacion',
                'managed': False,
            },
        ),
    ]
