# Generated by Django 4.0.4 on 2022-05-10 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0003_delete_authgroup_delete_authgrouppermissions_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Barrios',
            fields=[
                ('idbarrios', models.IntegerField(db_column='idBarrios', primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=45)),
                ('descripcion', models.TextField()),
            ],
            options={
                'db_table': 'barrios',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Ciudad',
            fields=[
                ('idciudad', models.IntegerField(db_column='idCiudad', primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=45)),
                ('descripcion', models.TextField()),
            ],
            options={
                'db_table': 'ciudad',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('iddepartamento', models.IntegerField(db_column='idDepartamento', primary_key=True, serialize=False)),
                ('nombre_departamento', models.CharField(max_length=45)),
                ('descripcion', models.TextField()),
            ],
            options={
                'db_table': 'departamento',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Desparasitacion',
            fields=[
                ('iddesparasitacion', models.IntegerField(db_column='idDesparasitacion', primary_key=True, serialize=False)),
                ('nombre_medicamento', models.CharField(max_length=80)),
                ('lote', models.CharField(max_length=45)),
                ('labaratorio', models.CharField(max_length=45)),
                ('registro_invima', models.CharField(max_length=80)),
                ('indicaciones', models.TextField()),
                ('contraindicaciones', models.TextField()),
                ('dirigido', models.CharField(max_length=80)),
                ('fecha_creacion', models.DateField()),
                ('fecha_vencimiento', models.DateField()),
                ('composicion', models.TextField()),
                ('cantidad_composicion', models.CharField(max_length=100)),
                ('cuidados', models.TextField()),
                ('fecha_aplicacion', models.DateField()),
                ('hora_aplicacion', models.TimeField()),
                ('proxima_fecha', models.DateField()),
                ('proxima_hora', models.TimeField()),
                ('cantidad_aplicada', models.CharField(max_length=80)),
            ],
            options={
                'db_table': 'desparasitacion',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EsquemaVacunacion',
            fields=[
                ('idesquema_vacunacion', models.IntegerField(db_column='idEsquema_vacunacion', primary_key=True, serialize=False)),
                ('vacuna_aplicada', models.CharField(max_length=60)),
                ('dosis_aplicadas', models.CharField(max_length=45)),
                ('dosis_aplicar', models.CharField(max_length=45)),
                ('dosis_faltantes', models.CharField(max_length=100)),
                ('fecha_aplicacion', models.DateField()),
                ('hora_aplicacion', models.TimeField()),
                ('proxima_fecha', models.DateField()),
                ('cantidad_aplicada', models.CharField(max_length=80)),
                ('zona_aplicada', models.CharField(max_length=80)),
                ('via_aplicada', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'esquema_vacunacion',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Habitat',
            fields=[
                ('idhabitat', models.AutoField(db_column='idHabitat', primary_key=True, serialize=False)),
                ('tipo_habitat', models.CharField(max_length=45)),
                ('descripcion', models.TextField()),
            ],
            options={
                'db_table': 'habitat',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Localidades',
            fields=[
                ('idlocalidades', models.IntegerField(db_column='idLocalidades', primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=80)),
                ('descripcion', models.TextField()),
            ],
            options={
                'db_table': 'localidades',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Mascotas',
            fields=[
                ('idmascotas', models.AutoField(db_column='idMascotas', primary_key=True, serialize=False)),
                ('tipo_animal', models.CharField(max_length=45)),
                ('clasificacion_animal', models.CharField(max_length=80)),
                ('nombre', models.CharField(max_length=45)),
                ('sexo', models.CharField(max_length=45)),
                ('fecha_nacimiento', models.DateField()),
                ('alimentacion', models.CharField(max_length=45)),
                ('comportamientos', models.TextField()),
                ('habitos', models.TextField()),
                ('sintomas', models.TextField()),
                ('caracteristicas_fisicas', models.TextField()),
            ],
            options={
                'db_table': 'mascotas',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Municipio',
            fields=[
                ('idmunicipio', models.IntegerField(db_column='idMunicipio', primary_key=True, serialize=False)),
                ('nombre_municipio', models.CharField(max_length=45)),
                ('descripcion', models.TextField()),
            ],
            options={
                'db_table': 'municipio',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Profesion',
            fields=[
                ('idprofesion', models.IntegerField(db_column='idProfesion', primary_key=True, serialize=False)),
                ('tipo_profesion', models.CharField(max_length=45)),
                ('descripcion', models.TextField()),
            ],
            options={
                'db_table': 'profesion',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ResumenServicio',
            fields=[
                ('idresumen_servicio', models.IntegerField(db_column='idResumen_servicio', primary_key=True, serialize=False)),
                ('descripcion_servicio', models.TextField()),
                ('productos_utilizados', models.TextField()),
                ('elementos_utilizados', models.TextField()),
                ('fecha_servicio', models.DateField()),
                ('hora_servicio', models.TimeField()),
                ('incovenientes', models.TextField()),
            ],
            options={
                'db_table': 'resumen_servicio',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TipoDocumento',
            fields=[
                ('idtipo_documento', models.IntegerField(db_column='idTipo_documento', primary_key=True, serialize=False)),
                ('nombre_documento', models.CharField(max_length=45)),
                ('descripcion', models.TextField()),
            ],
            options={
                'db_table': 'tipo_documento',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='Desparacitacion',
        ),
        migrations.DeleteModel(
            name='EsquemaVanucacion',
        ),
        migrations.DeleteModel(
            name='Mascota',
        ),
        migrations.DeleteModel(
            name='ResumenDelServicio',
        ),
    ]
